---

language: php

env:
    - CSS=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

php:
    - "7.0"

before_script:
    - "bash -c 'source ~/.nvm/nvm.sh; nvm install 6'"
    - "bash -c 'source ~/.nvm/nvm.sh; nvm use 6; npm install'"

script:
    - "bash -c 'source ~/.nvm/nvm.sh; nvm use 6; sh ./_tests/css.sh'"
    - "bash -c 'source ~/.nvm/nvm.sh; nvm use 6; sh ./_tests/javascript.sh'"
    - "sh ./_tests/php.sh"
    - "php ./_tests/translations.php"
