---

name: Update Submodules

on:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
          submodules: true

      - name: Setup PHP
        uses: shivammathur/setup-php@1.8.7
        with:
          php-version: '7.4'
          tools: composer
        
      - name: Initialize Submodules 
        run: git submodule update --init

      - name: Update Icons
        run: |
          cd _images/icons
          git pull origin master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "Automatic update of Icons Submodule"
          title: "Automatic update of Icons Submodule"
          branch: "update-icons-submodule"
          path: _lang
        env:
          GITHUB_TOKEN: ${{ secrets.RABBITBOT_TOKEN }}

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
