name: Update Translations from Source

on:
  push:
    branches:
      - master
      - auto-update-translations
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup GitHub Checkout
      uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: true
    - name: Setup PHP Action
      uses: shivammathur/setup-php@1.8.7
      with:
        php-version: '7.4'
        tools: composer
    - name: Initialize and update submodules
      run: git submodule init && git submodule update --force --rebase
    - name: Install Composer Dependencies
      run: cd _backend && composer install
    - name: Build website
      run: |
        npm install
        gulp      
    - name: Update Translations from Source
      run: php _backend/Console/Translation.php
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "Automatic update of translations files from source"
        title: "Automatic update of translations files from source"
        branch: "auto-update-translation"
      env:
        GITHUB_TOKEN: ${{ secrets.RABBITBOT_TOKEN }}
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
